###  Quadratic rough Heston model
$$
\begin{aligned}
dS_t&=S_t\sqrt{V_t}dW_t \\
V_t&=a(Z_t-b)^2+c
\end{aligned}
$$
where $W$ is a Brownian motion and $a,\,b,\,c>0$. This model is of rought Heston type, in the sense that weighted past price returns are drivers of the volatility dynamics:
$$Z_t=\int_0^t(t-s)^{\alpha-1}\frac{\lambda}{\Gamma(\alpha)}(\theta_0(s)-Z_s)ds+\int_0^t(t-s)^{\alpha-1}\frac{\lambda}{\Gamma(\alpha)}\eta\sqrt{V_s}dW_s$$
with $\alpha\in(1/2,\,1),\,\lambda>0,\,\eta>0$ and $\theta_0$ a deterministic function.

### Generate the parameters for the quadratic rough Heston model


#### $\Theta = \{\alpha,\lambda, a, b, c, Z_0\}\in\mathbb{R}^6$
Old version: $\alpha\in(0.5, 0.7),\, \lambda\in(0.1, 2), \, a\in(0.1, 1),\ b\in(0.01,1),\,c\in(0.0001, 0.01),\,Z_0\in(0.01, 0.3)$

New version: $\alpha\in(0.5, 0.7),\, \lambda\in(0.5, 1.5), \, a\in(0.1, 0.75),\ b\in(0.05,0.5),\,c\in(0.0001, 0.01),\,Z_0\in(0.05, 0.3)$

In [2]:
import numpy as np
import scipy.stats as st
%config Completer.use_jedi=False
import matplotlib.pyplot as plt
import pandas as pd
from scipy.stats import norm
from scipy.optimize import bisect
from utils import *

In [3]:
# Z0 = 0.1
# alpha = 0.55
# a = 0.384
# b = 0.095
# c = 0.0025
# Lambda = 1.2

# qrheston_params = {'alpha': alpha, 'Lambda': Lambda, 'a': a, 'b': b, 'c': c, 'Z0': Z0}


In [4]:
N = 1000000
np.random.seed(713)
alpha_N  = 0.5 + np.random.uniform(0.005, 0.2, N)
Lambda_N = np.random.uniform(0.8, 1.5, N)  # Lambda_N = np.random.uniform(0.5, 1.5, N)
a        = np.random.uniform(0.1, 0.75, N)
b        = np.random.uniform(0.075, 0.5, N)  
c        = np.random.uniform(0.002, 0.01, N)  #c= np.random.uniform(0.0001, 0.01, N)
Z0       = np.random.uniform(0.05, 0.3, N)

In [5]:
params = np.zeros((N, 6))
for i in range(N):
    tmp = [alpha_N[i], Lambda_N[i], a[i], b[i], c[i], Z0[i]]
    params[i] = np.round(tmp, 4)
    
# df = pd.DataFrame(params, index=None, columns=['alpha', 'lamba', 'a', 'b', 'c', 'Z0'])
# df.to_csv("Data/parameters.csv", index=None)

np.savetxt("Data/parameters_713.txt", params, fmt='%.4f')

In [ ]:
df = np.loadtxt("Data/impliedVols.txt")
df.shape
# df

In [ ]:
def parameter_fix_generator(N = 10, param_to_fix='a'):
    """
    Generate a data set wich includes one varying parameters, all other parameters are fixed
    """
    
    for i in range(N):
        

In [ ]:
a = pd.read_csv("Data/r.csv", index_col=0)
# np.sum(np.sum(a.isna()))
a

In [ ]:
b = np.loadtxt("Data/parameters.txt")
b[166:168]

In [1]:
from utils import *
impliedVol(0.6, 0.59, 1.0, 0.0236, r=0.05, q=0.1)

0.14511005768081037

In [2]:
40*np.exp(-0.1*0.25)-38

1.0123964811333082

### Viterbi Algorithm(HMM: hidden Markovian Model)
**States Space:** $S$ composed of $k$ states;

**The probability of states** $i$ as the initial states is $\pi_i$;

**Transition probability from states $i$ to $j$**: $a_{ij}$;

**Observation outputs:** $y_1, y_2, \dots, y_T$

The most possible sequence $x_1, x_2, \dots, x_k$ which produces the observation can be deduced by:

$$V_{1, k} = P(y_1|k)\cdot \pi_k$$
$$V_{t,k} = max_{x\in S}P(y_t|k)\cdot a_{x, k}\cdot V_{t-1, x}$$
Here $V_{t,k}$ is the probability of the first most probable state sequence $P(x_1, \dots, x_t, y_1,\dots, y_t)$ responsible for the first $t$ observations that have $k$ as its final state. Let $Ptr(k,t)$ bet he function that returns the value of $x$ used to compute $V_{t,k}$ if $t>1$ or $k$ if $t=1$. Then
$$x_T = argmax_{x\in S} V_{T, x}$$
$$x_t = Ptr(x_t, t)$$

In [4]:
stats = {'Healthy', 'Fever'}
observations = {'normal', 'cold', 'dizzy'}
starts_probability = {'Healthy': 0.6, 'Fever': 0.4}
transition_probability = {'Healthy': {'Healthy': 0.7, 'Fever': 0.3}, 'Fever': {'Healthy': 0.4, 'Fever': 0.6}}
emission_probability = {'Healthy': {'normal': 0.5, 'cold': 0.4, 'dizzy': 0.1}, 'Fever': {'normal': 0.1, 'cold': 0.3, 'dizzy': 0.6}}

In [5]:
import scipy

In [14]:
# A = np.diag(np.ones(10))
B = np.ones((10, 10))*0.2
B[np.diag_indices_from(B)] = 1.0
B

array([[1. , 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 1. , 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 1. , 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 1. , 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 1. , 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 1. , 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 1. , 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 1. , 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 1. , 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 1. ]])

In [26]:
import pprint
pprint.pprint(np.round(scipy.linalg.cholesky(B, lower=True), 2))
# == scipy.linalg.cholesky(B, lower=False)

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.98, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.16, 0.97, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.16, 0.14, 0.96, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.16, 0.14, 0.12, 0.95, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.16, 0.14, 0.12, 0.11, 0.94, 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.16, 0.14, 0.12, 0.11, 0.09, 0.94, 0.  , 0.  , 0.  ],
       [0.2 , 0.16, 0.14, 0.12, 0.11, 0.09, 0.09, 0.93, 0.  , 0.  ],
       [0.2 , 0.16, 0.14, 0.12, 0.11, 0.09, 0.09, 0.08, 0.93, 0.  ],
       [0.2 , 0.16, 0.14, 0.12, 0.11, 0.09, 0.09, 0.08, 0.07, 0.93]])


In [29]:
L = scipy.linalg.cholesky(B, lower=True)
X = np.random.normal(size=10)
np.dot(L, X)

array([ 1.61781137, -0.75480235,  1.36867169, -0.42302054, -0.38487444,
       -0.09521844, -0.68345853,  0.22749949,  0.05407973, -1.34108928])